name: ✨ 功能请求
description: 建议一个新功能
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        感谢您提出功能建议！

  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 您遇到的问题是什么？
      placeholder: 我总是很沮丧当...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案
      description: 您希望如何解决这个问题？
      placeholder: 我希望能够...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 您考虑过哪些替代解决方案或功能？

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 这个功能对您有多重要？
      options:
        - 低 - Nice to have
        - 中 - 会提高体验
        - 高 - 对我的工作流程很关键
    validations:
      required: true

  - type: dropdown
    id: willing
    attributes:
      label: 贡献意愿
      description: 您愿意帮助实现这个功能吗？
      options:
        - 是，我可以提交PR
        - 是，我可以帮助测试
        - 否，但我可以提供反馈
        - 否
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 附加信息
      description: 添加任何其他关于功能请求的信息、截图或示例

  - type: checkboxes
    id: terms
    attributes:
      label: 检查清单
      description: 在提交前请确认
      options:
        - label: 我已经搜索了现有的issues，没有找到重复的
          required: true
        - label: 这个功能符合项目的目标和范围
          required: true

